version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_USER=appuser
      - DB_PASSWORD=apppassword
    depends_on:
      db:
        condition: service_healthy

  db:
    build:
      context: .
      dockerfile: mysql.Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-yourpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-defsecdb}
      MYSQL_USER: ${MYSQL_USER:-appuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-apppassword}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-yourpassword}"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 40s
